server:
  port: 3306
spring:
  security:
    basic:
      enabled: false
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:mysql://localhost:3306/new_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    # url: jdbc:sqlserver://localhost:1433;databaseName=sss;encrypt=true;trustServerCertificate=true
    # username: sa
    # password: MyPass@word
    username: root
    password: 1234
  devtools:
    restart:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create #조심해서 사용할것
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        use_nationalized_character_data: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
