server:
  address: localhost
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/new_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: root
    password: 1234

  # 실행되는 쿼리 콘솔에 출력
  # 콘솔창에 출력되는 쿼리를 가독성이 좋게 포맷팅
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

      # 쿼리에 물음표로 출력되는 바인드 파라미터 출력
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

    # Entity 설정을 참고하여 Spring Application 실행 시점에 Hibernate에서 자동으로 DDL을 생성한다
    # 필요한 Database의 Table 설정들을 자동으로 수행해준다
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
