// 근로시간확인용 json

export const geunlotimelist =[
    {
        "id":1,
        "geunloName": "나이스",
        "sojeonggeunlo": 176,
        "chonggeunlo": 176,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 0,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 0,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 3,
        "gyeolgeun": 0
    },
    {
        "id":2,
        "geunloName": "네모",
        "sojeonggeunlo": 176,
        "chonggeunlo": 180,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 2,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 2,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 4,
        "gyeolgeun": 0
    },
    {
        "id":3,
        "geunloName": "세모",
        "sojeonggeunlo": 176,
        "chonggeunlo": 195,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 4,
        "hyuilgeunlo": 9,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 6,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 10,
        "gyeolgeun": 0
    },
    {
        "id":4,
        "geunloName": "사각",
        "sojeonggeunlo": 176,
        "chonggeunlo": 176,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 0,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 0,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 15,
        "gyeolgeun": 0
    },
    {
        "id":5,
        "geunloName": "사각",
        "sojeonggeunlo": 176,
        "chonggeunlo": 176,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 0,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 0,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 15,
        "gyeolgeun": 0
    },
    {
        "id":6,
        "geunloName": "사각",
        "sojeonggeunlo": 176,
        "chonggeunlo": 176,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 0,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 0,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 15,
        "gyeolgeun": 0
    },
    {
        "id":7,
        "geunloName": "사각",
        "sojeonggeunlo": 176,
        "chonggeunlo": 176,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 0,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 0,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 15,
        "gyeolgeun": 0
    },{
        "id":8,
        "geunloName": "사각",
        "sojeonggeunlo": 176,
        "chonggeunlo": 176,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 0,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 0,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 15,
        "gyeolgeun": 0
    },
    {
        "id":9,
        "geunloName": "사각",
        "sojeonggeunlo": 176,
        "chonggeunlo": 176,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 0,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 0,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 15,
        "gyeolgeun": 0
    },
    {
        "id":14,
        "geunloName": "사각",
        "sojeonggeunlo": 176,
        "chonggeunlo": 176,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 0,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 0,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 15,
        "gyeolgeun": 0
    },{
        "id":24,
        "geunloName": "사각",
        "sojeonggeunlo": 176,
        "chonggeunlo": 176,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 0,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 0,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 15,
        "gyeolgeun": 0
    },
    {
        "id":34,
        "geunloName": "사각",
        "sojeonggeunlo": 176,
        "chonggeunlo": 176,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 0,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 0,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 15,
        "gyeolgeun": 0
    },{
        "id":44,
        "geunloName": "사각",
        "sojeonggeunlo": 176,
        "chonggeunlo": 176,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 0,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 0,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 15,
        "gyeolgeun": 0
    },{
        "id":54,
        "geunloName": "사각",
        "sojeonggeunlo": 176,
        "chonggeunlo": 176,
        "gibongeunlo": 176,
        "yeonjanggeunlo": 0,
        "hyuilgeunlo": 0,
        "hyuilyeonjanggeunlo": 0,
        "yagangeunlo": 0,
        "juhyuil": 0,
        "gonghyuil": 0,
        "yeoncha": 15,
        "gyeolgeun": 0
    },
]